# Generated by Django 5.1.5 on 2025-01-20 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title should be unique and under 128 char.', max_length=128, unique=True)),
                ('json_body', models.JSONField(help_text='All content of body should be save base on json.')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['title', 'pub_date', 'is_active'], name='api_app_art_title_3447a3_idx')],
            },
        ),
    ]
