# Generated by Django 5.1.5 on 2025-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Title should be unique and under 128 char.', max_length=128),
        ),
    ]
